### ISSUE TITLE
So many compile errors, did some tried ever this plugin?

### ISSUE THREAD

**Issue by prashantraval91185** [hirenreshamwala/laravel-inertia-element-ui-crud-vue3#1]
Hi,

I got more than 50 errors regarding lodash, the element-plus can't resolve it. Does anyone have a suggestion?

Thanks

**Comment by hirenreshamwala** [comment]
Please share the errors.

**Comment by prashantraval91185** [comment]
Thanks for your response, but currently I move with a new UI, I will post again with a screenshot and details once set up it again later.

**Comment by jjmontgo** [comment]
Here are all the errors I get.

`ERROR in ./resources/js/app.js 6:0-48
Module not found: Error: Can't resolve 'element-plus/lib/theme-chalk/index.css' in '/var/www/lms.divergent.io/resources/js'

ERROR in ./node_modules/element-plus/es/components/calendar/src/date-table2.mjs 3:0-49
Module not found: Error: Can't resolve 'dayjs/plugin/localeData' in '/var/www/lms.divergent.io/node_modules/element-plus/es/components/calendar/src'
Did you mean 'localeData.js'?
BREAKING CHANGE: The request 'dayjs/plugin/localeData' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/element-plus/es/components/date-picker/src/date-picker.mjs 3:0-63
Module not found: Error: Can't resolve 'dayjs/plugin/customParseFormat' in '/var/www/lms.divergent.io/node_modules/element-plus/es/components/date-picker/src'
Did you mean 'customParseFormat.js'?
BREAKING CHANGE: The request 'dayjs/plugin/customParseFormat' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/element-plus/es/components/date-picker/src/date-picker.mjs 4:0-57
Module not found: Error: Can't resolve 'dayjs/plugin/advancedFormat' in '/var/www/lms.divergent.io/node_modules/element-plus/es/components/date-picker/src'
Did you mean 'advancedFormat.js'?
BREAKING CHANGE: The request 'dayjs/plugin/advancedFormat' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/element-plus/es/components/date-picker/src/date-picker.mjs 5:0-49
Module not found: Error: Can't resolve 'dayjs/plugin/localeData' in '/var/www/lms.divergent.io/node_modules/element-plus/es/components/date-picker/src'
Did you mean 'localeData.js'?
BREAKING CHANGE: The request 'dayjs/plugin/localeData' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/element-plus/es/components/date-picker/src/date-picker.mjs 6:0-49
Module not found: Error: Can't resolve 'dayjs/plugin/weekOfYear' in '/var/www/lms.divergent.io/node_modules/element-plus/es/components/date-picker/src'
Did you mean 'weekOfYear.js'?
BREAKING CHANGE: The request 'dayjs/plugin/weekOfYear' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/element-plus/es/components/date-picker/src/date-picker.mjs 7:0-45
Module not found: Error: Can't resolve 'dayjs/plugin/weekYear' in '/var/www/lms.divergent.io/node_modules/element-plus/es/components/date-picker/src'
Did you mean 'weekYear.js'?
BREAKING CHANGE: The request 'dayjs/plugin/weekYear' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/element-plus/es/components/date-picker/src/date-picker.mjs 8:0-47
Module not found: Error: Can't resolve 'dayjs/plugin/dayOfYear' in '/var/www/lms.divergent.io/node_modules/element-plus/es/components/date-picker/src'
Did you mean 'dayOfYear.js'?
BREAKING CHANGE: The request 'dayjs/plugin/dayOfYear' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/element-plus/es/components/date-picker/src/date-picker.mjs 9:0-55
Module not found: Error: Can't resolve 'dayjs/plugin/isSameOrAfter' in '/var/www/lms.divergent.io/node_modules/element-plus/es/components/date-picker/src'
Did you mean 'isSameOrAfter.js'?
BREAKING CHANGE: The request 'dayjs/plugin/isSameOrAfter' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/element-plus/es/components/date-picker/src/date-picker.mjs 10:0-57
Module not found: Error: Can't resolve 'dayjs/plugin/isSameOrBefore' in '/var/www/lms.divergent.io/node_modules/element-plus/es/components/date-picker/src'
Did you mean 'isSameOrBefore.js'?
BREAKING CHANGE: The request 'dayjs/plugin/isSameOrBefore' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/element-plus/es/components/time-picker/src/time-picker.mjs 3:0-63
Module not found: Error: Can't resolve 'dayjs/plugin/customParseFormat' in '/var/www/lms.divergent.io/node_modules/element-plus/es/components/time-picker/src'
Did you mean 'customParseFormat.js'?
BREAKING CHANGE: The request 'dayjs/plugin/customParseFormat' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/element-plus/es/components/time-select/src/time-select.mjs 3:0-63
Module not found: Error: Can't resolve 'dayjs/plugin/customParseFormat' in '/var/www/lms.divergent.io/node_modules/element-plus/es/components/time-select/src'
Did you mean 'customParseFormat.js'?
BREAKING CHANGE: The request 'dayjs/plugin/customParseFormat' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

webpack compiled with 12 errors`

**Comment by hirenreshamwala** [comment]
In the latest version of the element plus CSS, the path has been changed.

https://element-plus.org/en-US/guide/quickstart.html#full-import

You need to change your app.js

From:
```
import "element-plus/lib/theme-chalk/index.css";
```

To:
```
import 'element-plus/dist/index.css'
```

Also, you need to change your webpack.mix.js

https://github.com/element-plus/element-plus/issues/4132

**Comment by jjmontgo** [comment]
Thanks!
